TIG-446 adds random image to action fact step three using tig api
TakingITGlobal/commit2act pull request #100
Opened 2024-02-12 07:38 UTC by polygonart6777

Uses the TIG API: https://research.tigweb.org/gg/api/submissions/4965 
To show a random image from the given list on step three of the log action flow.

![Screenshot from 2024-02-11 23-36-29](https://github.com/UBC-CIC/commit2act/assets/14957396/347d4114-e032-40d2-9f50-70fd3f412e94)

2024-02-14 23:47 UTC, klancashire requested changes
Looks great but as you noted on the clickup, the caption is getting lost in lighter images. I noticed in the Figma design there's a very slight dark transparent background on the caption so I would add this and it should love this issue. 

![Screenshot 2024-02-14 at 3 45 14 PM](https://github.com/TakingITGlobal/commit2act/assets/8181538/8b444991-ae86-4cfa-8df4-12e75bbeb253)

2024-02-15 14:42 UTC, stephenbelyea reviewed
Looks good - small not on extracting the image render function as it's own component. Otherwise, also agree with @klancashire's note on the caption having a background. 

Nicely done!

2024-02-15 14:42 UTC, stephenbelyea commented on src/components/logAction/ActionFact.js
> +  const renderImage = () =>
Instead of inlining this as a `renderImage` function, can we extract as it's own component? It can live within the same file, it's just nice to reduce the render logic within a component function to help cut down on potential re-rendering triggered by state or props changes!

2024-02-15 14:42 UTC, stephenbelyea commented on src/components/logAction/ActionFact.js
> +            height="250px"
Should we opt for a `max-height` here to reduce risks of stretching our image?

2024-02-15 14:42 UTC, stephenbelyea commented on src/hooks/use-action-fact-image.js
> +export const useActionFactImage = () => {
Great to see dedicated custom hooks in use, especially with proper `try`/`catch` error handling! Nicely done :D

2024-02-16 05:59 UTC, polygonart6777 commented on src/components/logAction/ActionFact.js
> +  const renderImage = () =>
I'm not sure what you mean, what are the unnecessary re-renders you are seeing?

2024-02-16 06:02 UTC, merged

2024-02-22 20:12 UTC, stephenbelyea commented on src/components/logAction/ActionFact.js
> +  const renderImage = () =>
I didn't specifically observe any, but if I was tracking more carefully the browser performance we'd probably see some with any props changes. This is more just a pattern I've seen a lot in the C2A codebase where large components have multiple render functions, rather than breaking out into separate components.